# Generated by Django 2.0.1 on 2018-10-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_group_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='students',
            new_name='student',
        ),
    ]
