# Generated by Django 2.0.1 on 2018-10-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181015_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_groups', to='user.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_groups', to='user.Student')),
            ],
        ),
    ]
