# Generated by Django 2.0.1 on 2018-10-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Group',
        ),
    ]
