# Generated by Django 2.1.2 on 2018-11-03 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181027_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesheet',
            name='group',
        ),
        migrations.RemoveField(
            model_name='attendancesheet',
            name='student',
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='registered_students',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.RegisteredGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='date',
            field=models.CharField(default='teste', max_length=25),
        ),
    ]
