# Generated by Django 2.1.2 on 2018-11-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181103_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/students/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_code',
            field=models.TextField(default=0, max_length=2048),
            preserve_default=False,
        ),
    ]
