# Generated by Django 2.1.2 on 2018-11-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181105_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='media/students/no-img.jpg', upload_to='media/students'),
        ),
    ]
