# Generated by Django 2.1.2 on 2018-11-13 18:25

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181105_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesheet',
            name='registered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendace_sheet', to='user.RegisteredGroup'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='students/no-img.jpg', upload_to=user.models.unique_file_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo_code',
            field=models.TextField(default=user.models.photo_code_creater, max_length=2048),
        ),
    ]
