# Generated by Django 2.1.3 on 2018-11-22 16:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20181113_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesheet',
            name='time',
            field=models.CharField(choices=[('0', '06:00 - 08:00'), ('1', '08:00 - 10:00'), ('2', '10:00 - 12:00'), ('3', '12:00 - 14:00'), ('4', '14:00 - 16:00'), ('5', '16:00 - 18:00'), ('6', '18:00 - 20:00'), ('7', '20:00 - 22:00'), ('8', '22:00 - 00:00')], default=14, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='registered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sheet', to='user.RegisteredGroup'),
        ),
    ]
