# Generated by Django 2.1.1 on 2018-11-26 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_registeredgroup_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredgroup',
            name='delete_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeredgroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
